version: "3.7"
services:
  
  server:
    image: d-bank-server
    build: 
      context: .
      dockerfile: ./back-end/Dockerfile
    ports:
      - 4201:4201
    environment:
      PORT: 4201
      REPLICAS: 16
      DDELAY: 2000

       
  app:
    image: d-bank-front-end
    build: 
      context: .
      dockerfile: ./front-end/Dockerfile
    ports:
      - 4200:4200
    depends_on: 
      - server