version: "3.7"
services:
  # db: 

  server:
    image: d-bank-server
    build: 
      context: .
      dockerfile: ./back-end/Dockerfile
    ports:
      - 4201:4201
    environment:
      port: 4201
      replicas: 16
      ddelay: 2000
      logLevel: 4
       
  app:
    image: d-bank-front-end
    build: 
      context: .
      dockerfile: ./front-end/Dockerfile
    ports:
      - 4200:4200
    depends_on: 
      - server